### ISSUE TITLE
[Windows] Unable to create report

### ISSUE THREAD

**Issue by Cy4n1d3** [Alexia/php7mar#13]
Hey,
great project, thanks so far :)
Under Windows Server there is a small problem with the name of the generated report file:

In reporter.php at L78 (https://github.com/Alexia/php7mar/blob/master/classes/reporter.php#L78):
``` 	$this->fullFilePath = $this->reportFolder.date('Y-m-d H:i:s ').basename($this->projectPath, '.php').".md";```

The ':' inside the date-string lead to a filesystem error as ':' is not allowed inside file names under windows. I fixed it locally by using dots instead but maybe you can change it globally so it is working under all environments by default?

Thanks and regards

**Comment by kristian-b** [comment]
I had this issue too. It would be great if it could be fixed.

**Comment by Alexia** [comment]
https://github.com/Alexia/php7mar/releases/tag/v0.1.1-alpha
