### ISSUE TITLE
Notice under Windows when folder contains space

### ISSUE THREAD

**Issue by Veve2** [Alexia/php7mar#16]
As soon as the folder contains a space, I've got this notice continuously (Windows 7 with wampserver 3.0.0):
`Notice: Undefined index: line in D:\wamp64\\www\php7mar\mar.php on line 126`

**Comment by emanwebdev** [comment]
+1

**Comment by Alexia** [comment]
I pushed a fix up to the master branch if you would like to test it.

**Comment by Veve2** [comment]
I've tested it, it works, thank!
