### ISSUE TITLE
Comments out lines are not ignored

### ISSUE THREAD

**Issue by virtualmarc** [Alexia/php7mar#2]
Comments should not be scanned:

```php
####/XXXXXX/XXXXXXXX.php
* reservedNames
 * Line 99:                                                     // get class object
 * Line 179:                            // get class object
```

**Comment by Alexia** [comment]
Unfortunately it will not ignore what looks like code in comments.  However, that does show the check for reserved class/interface/trait names needs to be improved.  I will look at that.

**Comment by Alexia** [comment]
This should be fixed as of: https://github.com/Alexia/php7mar/commit/a163f4a24e4e2039702e30d57e34853c9e60b14a
