### ISSUE TITLE
PHP Warning:  Unterminated comment starting line 1 in classes/tests/critical.php on line 71

### ISSUE THREAD

**Issue by pierrocknroll** [Alexia/php7mar#22]
:)

**Comment by Alexia** [comment]
I am not seeing what that error is pointing out?

**Comment by zbrag** [comment]
Using php5.6 I also get this error, it has something to do with the `$tokens = token_get_all("<?php ".$matches[1]."?>");` 
I haven't read the code so I won't try to guess what could be the fix 😄

**Comment by denezt** [comment]
Almost a year and a half later you get an answer: 
install the php#-tokenizer
For example if you are using php7 then you need to install php7-tokenizer.
**ubuntu:**
apt-get install php7-tokenizer
**SUSE:**
zypper install php7-tokenizer
