### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by lphooge** [Alexia/php7mar#28]
When running mar.php i get the following error:
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /usr/local/share/php7mar/mar.php on line 58

Maybe php7mar itelf needs PHP 7? I don't see any mention of that in the readme.

**Comment by cwhsu1984** [comment]
Yes, you're required to install PHP 7 before using php7mar.

**Comment by Alexia** [comment]
Just needs 5.4 as a minimum to run it and only 7.0 only needs to be installed for running syntax checks against 7.0.
