### ISSUE TITLE
MAR reports on itself

### ISSUE THREAD

**Issue by xPaw** [Alexia/php7mar#9]
Perhaps filtering it would be a good option? It catches all the tests as violations of themselves.

**Comment by Alexia** [comment]
I am not sure what you mean.  Do you mean the testcases.php file?

**Comment by xPaw** [comment]
If you run a scan on your home directory, and php7mar is inside, it will include that in the report.

**Comment by Alexia** [comment]
Yep, that will happen.  MAR should be move outside of where it is scanning to avoid that.

**Comment by xPaw** [comment]
It's not a huge problem. But perhaps ignoring php7mar by namespace or path could be added.
